Android
bitwarden/passwordless-docs pull request #71
Opened 2023-12-20 11:25 UTC by jonashendrickx

2023-12-22 11:43 UTC, abergs commented
Since it contains TODO's I'm guessing this is not yet ready for review, marking as draft.

2024-01-31 16:24 UTC, jrmccannon submitted a review, later dismissed

2024-01-31 16:24 UTC, jrmccannon commented on src/guide/frontend/android.md
> +   # Identifier for your server, for example 'example.com' if your backend is hosted at https://example.com.
```suggestion
   // Identifier for your server, for example 'example.com' if your backend is hosted at https://example.com.
```

2024-01-31 16:24 UTC, jrmccannon commented on src/guide/frontend/android.md
> +   # This is where your Facet ID goes
```suggestion
   // This is where your Facet ID goes
```

2024-01-31 16:24 UTC, jrmccannon commented on src/guide/frontend/android.md
> +   # Where your backend is hosted
```suggestion
   // Where your backend is hosted
```

2024-01-31 16:24 UTC, jrmccannon commented on src/guide/frontend/android.md
> +   # Passwordless.dev server, change for self-hosting
```suggestion
   // Passwordless.dev server, change for self-hosting
```

2024-01-31 16:24 UTC, jrmccannon commented on src/guide/frontend/android.md
> +You can find the same application [here](https://www.github.com/bitwarden/passwordless-android).
Maybe have this point to the sample app? 
https://github.com/bitwarden/passwordless-android/tree/main/app

And provide a README on how to get it up and running locally

2024-01-31 20:44 UTC, abergs requested changes
Nice write-up - lots of good knowledge collected here.

I do think we can iterate on it to make it read similar to the existing guides:

* https://docs.passwordless.dev/guide/frontend/javascript.html
* https://docs.passwordless.dev/guide/frontend/aspnet.html

Suggestion: I think we could add a little bit of "hand holding", and perhaps move the technicalities of facetid and assetlinking further down, first showing installation and usage of the sdk?

2024-01-31 20:44 UTC, abergs commented on src/guide/frontend/android.md
> +- Android 7.0 (API level 24) or higher
I don't think this version of Android supports Passkeys, I think device bound passkeys were added on Android 9 and the CredMan "modern passkeys were added in Android 14.

https://developers.google.com/identity/passkeys/supported-environments

2024-01-31 20:44 UTC, abergs commented on src/.vuepress/config.js
question: Why is this commited? We have a config.ts - this seems to be a misstake?

2024-02-01 09:47 UTC, abergs commented
@fschillingeriv Hey Fred, I'm wondering if you could help us edit this technical documentation for our Android SDK?

While the page current has great detailed knowledge, I feel like we should adapt the way we present it. Not all of it is directly related to Passwordless.dev and is more "creating an android app".

Perhaps @mpbw2 or @fedemkr could also shime in and just point out what we could put in a sub-page and just link to? https://android.passwordless-docs.pages.dev/

2024-02-02 12:11 UTC, abergs commented on src/guide/frontend/android.md
> +   - See (API documentation)[https://docs.passwordless.dev/guide/api.html#signin-verify]
Broken link syntax, change to []()

2024-02-02 14:58 UTC, fschillingeriv commented on src/guide/frontend/android.md
> +
Does it make sense to preface this with information about where to add this data class (e.g. like you do when you say "In your application's AndroidManifest.xml")?

2024-02-02 14:59 UTC, fschillingeriv commented on src/guide/frontend/android.md
> +In your `AndroidManifest.xml`, you will need to add the following permissions:
Small editorial comment; wherever you write ", you will need to add..." can be shortened to ", add..." for brevity's sake.

2024-02-02 15:00 UTC, fschillingeriv commented on src/guide/frontend/android.md
> +
Is it "our" assetlinks.json file or "their" assetlinks.json file? Asking b/c in the example it looks like it's hosted under their domain.

2024-02-02 15:00 UTC, fschillingeriv commented on src/guide/frontend/android.md
> +To obtain the Facet ID continue the steps below, the facet id typically looks like:
Would suggest capitalizing "ID" to match the others.

2024-02-02 15:01 UTC, fschillingeriv commented on src/guide/frontend/android.md
> +This command will print detailed information about the keystore entry with the specified alias, including information about the certificate, its validity, and other details. It's commonly used in And
Would suggest changing "This command" to "The following command" to draw attention to the fact that you're describing what's in the tabs below.

2024-02-02 15:02 UTC, fschillingeriv commented on src/guide/frontend/android.md
> +Go to the root directory of the project from the terminal and run the below command
Maybe add ":" at the end.

2024-02-02 15:02 UTC, fschillingeriv commented on src/guide/frontend/android.md
> +Put this SHA256 along with your root android package name in your backend to generate `assetlinks.json` for your app at `https://yourexample.com/.well-known/assetlinks.json`.
Should "android"  be capitalized here?

2024-02-02 15:02 UTC, fschillingeriv commented on src/guide/frontend/android.md
> +If you are using `example-nodejs-backend`. then just put these 2 values in your `.env` file.
I think that "." should be a ",".

2024-02-02 15:03 UTC, fschillingeriv commented on src/guide/frontend/android.md
> +Or you can set the Context of PasswordlessClient manually: Ensure the context is set to the current `Activity`.
I think that ":" should be a "." or a ",".

2024-02-02 15:04 UTC, fschillingeriv commented on src/guide/frontend/android.md
> +   - (Required) Specify the username for the credential.
Would always recommend putting required steps above optional ones, unless the order they're done in matters.

2024-02-02 15:05 UTC, fschillingeriv commented on src/guide/frontend/android.md
> +3. **Call `PasswordlessClient.register()`**
Add ":" to match steps 1 & 2.

2024-02-02 16:43 UTC, mmccabe4 reviewed
just a few comments

2024-02-02 16:43 UTC, mmccabe4 commented on src/guide/frontend/android.md
> +In your application's `AndroidManifest.xml`, you will then need to add the tag below under `manifest::application`:
Little confusing to read, perhaps "add the follow tag under manifest::application"

2024-02-02 16:43 UTC, mmccabe4 commented on src/guide/frontend/android.md
> +The `Facet ID` will be used at a later point in this guide to use as the `origin`.
This isnt an error necessarily, but sometimes shortening things can help them be more understandable. For example changing the line here to "will be used later in this guide as the `origin`. "

2024-02-07 13:57 UTC, Tyrrrz approved these changes

2024-02-07 13:57 UTC, Tyrrrz commented on src/guide/frontend/android.md
> +   // This is where your Facet ID goes
Would be nice to have an example, similar to above, so the user knows what the value should look like

2024-02-07 14:09 UTC, jrmccannon approved these changes

2024-02-07 15:12 UTC, merged